CREATE TABLE IF NOT EXISTS sys_message (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL COMMENT '消息标题',
  content TEXT COMMENT '消息内容',
  receiver_id BIGINT NOT NULL COMMENT '接收者ID',
  type VARCHAR(50) DEFAULT 'SYSTEM' COMMENT '消息类型',
  status INT DEFAULT 0 COMMENT '状态: 0-未读, 1-已读',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统消息表';