-- sys_role
ALTER TABLE sys_role ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_role ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sys_role ADD COLUMN deleted INT DEFAULT 0;

-- sys_permission
ALTER TABLE sys_permission ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_permission ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sys_permission ADD COLUMN deleted INT DEFAULT 0;

-- house_info
ALTER TABLE house_info ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE house_info ADD COLUMN deleted INT DEFAULT 0;

-- lease_contract
ALTER TABLE lease_contract ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE lease_contract ADD COLUMN deleted INT DEFAULT 0;

-- rent_bill
ALTER TABLE rent_bill ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE rent_bill ADD COLUMN deleted INT DEFAULT 0;

-- sys_message
ALTER TABLE sys_message ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sys_message ADD COLUMN deleted INT DEFAULT 0;

-- repair_order
ALTER TABLE repair_order ADD COLUMN deleted INT DEFAULT 0;

-- sys_dict_type
ALTER TABLE sys_dict_type ADD COLUMN deleted INT DEFAULT 0;

-- sys_dict_data
ALTER TABLE sys_dict_data ADD COLUMN deleted INT DEFAULT 0;
